---
- hosts: all
  become: true
  roles:
  - install_docker_and_components
  - swap_off
  - install_kubelet_kubeadm_kubectl
  - initialize_kubeadm
  - setup_kubeconfig
  - install_calico
  - generate_join-command